services:
  - type: web
    name: yt-dlp-downloader
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && apt-get update && apt-get install -y ffmpeg
    startCommand: gunicorn app:app --workers 1 --timeout 3600 --bind 0.0.0.0:$PORT
    envVars:
      PORT: 10000
